server:
  port: 8001
spring:
  application:
    name: demo-service
#  profiles: cloud
#  cloud:
#    config:
#      uri: http://localhost:8000
#      fail-fast: true
eureka:
#  client:
#    serviceUrl: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: instance2

#    registerWithEureka: false
#    fetchRegistry: false
#    instance:
#      appname: demo-service
