server:
  port: 8088
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka