server:
  port: 8089
spring:
  application:
    name: demo-client
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

demo-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8761,localhost:8661,localhost:8561
    ServerListRefreshInterval: 5000